import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "Next.js App",
    template: "%s | Next.js App",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-slate-50 text-slate-900">
        <div className="flex min-h-screen flex-col">
          <header className="sticky top-0 z-20 border-b border-slate-200/80 bg-white/85 backdrop-blur">
            <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-4">
              <Link href="/" className="text-lg font-bold tracking-tight text-slate-900">
                My Website
              </Link>
              <nav className="flex items-center gap-5 text-sm font-medium text-slate-600">
                <Link href="/about" className="transition-colors hover:text-slate-900">
                  About
                </Link>
                <Link href="/blog" className="transition-colors hover:text-slate-900">
                  Blog
                </Link>
                <Link href="/products" className="transition-colors hover:text-slate-900">
                  Products
                </Link>
              </nav>
            </div>
          </header>

          <div className="flex-1">{children}</div>

          <footer className="border-t border-slate-200 bg-white/70">
            <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-5 text-sm text-slate-600">
              <p>© 2026 My Website</p>
              <p>Built with Next.js</p>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}