import type { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex min-h-screen flex-col bg-slate-50 text-slate-900">
      <main className="mx-auto w-full max-w-5xl flex-1 px-6 py-10">{children}</main>

      <footer className="mt-10 border-t border-slate-200 bg-white/70">
        <div className="mx-auto flex w-full max-w-5xl items-center justify-between px-6 py-5 text-sm text-slate-600">
          <p>© 2026 My Website</p>
          <p>Built with Next.js</p>
        </div>
      </footer>
    </div>
  );
}
